<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Item;
use AppBundle\Entity\User;
use Doctrine\ORM\EntityRepository;

/**
 * ItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemRepository extends EntityRepository
{
    public function findAvailableMatches(Item $item, User $user): array
    {
        $qb = $this
            ->createQueryBuilder('i')
            ->leftJoin('i.user', 'iu')
            ->where('iu.location = :location')
            ->andWhere('i.category IN (:categories)')
            ->andWhere('i.value >= :min_value')
            ->andWhere('i.value <= :max_value')
            ->setParameters([
                'location' => $user->getLocation(),
                'min_value' => $item->getValue() - 3,
                'max_value' => $item->getValue() + 3,
                'categories' => $item->getCategoriesToMatchArray(),
            ]);

        return $qb->getQuery()->getResult();
    }
}
