<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Match;
use AppBundle\Entity\User;
use AppBundle\Entity\Item;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;
use Gedmo\SoftDeleteable\Query\TreeWalker\SoftDeleteableWalker;

/**
 * MatchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatchRepository extends EntityRepository
{
    /**
     * Return array of incoming item matches for given user
     *
     * @param User $user
     * @param int $status
     *
     * @return array
     */
    public function findMatchesByRespondent(User $user, int $status = Match::STATUS_ACCEPTED): array
    {
        $matches = $this->createQueryBuilder('m')
            ->leftJoin('m.itemRespondent', 'i')
            ->where('i.user = :user')
            ->andWhere('m.status = :status')
            ->setParameters([
                'user' => $user,
                'status' => $status,
            ])
            ->getQuery()
            ->getResult();

        return $matches;
    }

    /**
     * Return array of incoming item matches for given user
     *
     * @param User $user
     * @param int $status
     *
     * @return array
     */
    public function findMatchesByOwner(User $user, int $status = Match::STATUS_ACCEPTED): array
    {
        $matches = $this->createQueryBuilder('m')
            ->leftJoin('m.itemOwner', 'i')
            ->where('i.user = :user')
            ->andWhere('m.status = :status')
            ->setParameters([
                'user' => $user,
                'status' => $status,
            ])
            ->getQuery()
            ->getResult();

        return $matches;
    }

    /**
     * Return array of all related matches for given match
     *
     * @param Match $match
     *
     * @return array
     */
    public function deleteRelatedMathes(Match $match)
    {
        $result = $this->createQueryBuilder('m')
            ->delete()
            ->where('m.itemOwner IN (:itemOwner, :itemRespondent)')
            ->orWhere('m.itemRespondent IN (:itemOwner, :itemRespondent)')
            ->setParameters([
                'itemOwner' => $match->getItemOwner(),
                'itemRespondent' => $match->getItemRespondent(),
            ])
            ->getQuery()
            ->setHint(
                Query::HINT_CUSTOM_OUTPUT_WALKER,
                SoftDeleteableWalker::class
            )
            ->getResult();

        return $result;
    }

    /**
     * Delete all item matches
     *
     * @param Item $item
     *
     * @return void
     */
    public function deleteItemMatches(Item $item)
    {
        $this->createQueryBuilder('m')
            ->delete()
            ->where('m.itemOwner = :item OR m.itemRespondent = :item')
            ->andWhere('m.deletedAt IS NULL')
            ->setParameters([
                'item' => $item,
            ])
            ->getQuery()
            ->setHint(
                Query::HINT_CUSTOM_OUTPUT_WALKER,
                SoftDeleteableWalker::class
            )
            ->getResult();

        return;
    }
}
